export const initialData = {
  products: [
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      images: ['/example.jpg', '/example-2.webp'],
      finish: ['Ash', 'Oak', 'Walnut'],
      inStock: 10,
      price: 1800,
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      slug: 'aluminum-ottoman',
      tags: ['tag'],
      title: 'ALUMINUM OTTOMAN',
      series: 'alabaster',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'alabaster',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'capsule',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'lounge',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'alabaster',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'alabaster',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'capsule',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'lounge',
    },
    {
      description: `La Pepino is a collection of seating variations, built on the repeating pattern of cylindrical cushions, and supported by an organically shaped base. Every piece comes fully upholstered in customisable fabrics, and plays with the different points of contact between cushion and body.`,
      finish: ['Ash', 'Oak', 'Walnut'],
      images: ['/example.jpg', '/example-2.webp'],
      measurements: {
        depth: '60',
        width: '52',
        totalHeight: '90',
      },
      price: 1800,
      slug: 'aluminum-ottoman',
      title: 'ALUMINUM OTTOMAN',
      inStock: 10,
      tags: ['tag'],
      series: 'lounge',
    },
  ],
};
